graph LR
    %% Actors
    Admin[Administrator]

    %% Styles
    classDef actor fill:#ffffff,stroke:#000000,stroke-width:2px;
    classDef usecase fill:#ffffff,stroke:#000000,stroke-width:1px,rx:5,ry:5;
    class Admin actor;
    class UC19,UC20 usecase;

    %% Diagram
    subgraph Dashboard [Dashboard & Reports]
        direction TB
         style Dashboard fill:#ffffff,stroke:#000000,stroke-width:2px
        UC19([View Dashboard Overview])
        UC20([View Production Reports])
    end

    Admin --> UC19
    Admin --> UC20
